### ISSUE TITLE
Add delete functionality

### ISSUE THREAD

**Issue by contolini** [cfpb/hubot-acrogov#1]
Right now you can [add definitions](https://github.com/cfpb/hubot-acrogov/blob/master/src/acrogov.coffee#L37-L41) to the bot but you can't delete them. A `removeAcronym` method needs to be written to handle removals. Something like:

```
removeAcronym: (term) ->
  delete @cache[term.toUpperCase()]
  @robot.brain.data.acrogov = @cache
```

The command could be something like `hubot stop defining [term]`.

@higs4281 @hillaryj

**Comment by higs4281** [comment]
done.
