### ISSUE TITLE
Loading public acronyms

### ISSUE THREAD

**Issue by contolini** [cfpb/hubot-acrogov#4]
@higs4281 It looks like we only load the public acronyms if the private file doesn't exist. Don't we want to _always_ load public acronyms? From [acrogov.coffee](https://github.com/cfpb/hubot-acrogov/blob/master/src/acrogov.coffee#L37-L44):

```
fs.access acroPrivPath, fs.F_OK, (err) =>
  if err
    @loadPublicAcronyms()
    console.log("loaded public acronyms")
  else
    privateAcronyms = JSON.parse(fs.readFileSync(acroPrivPath, 'utf8'))
    Object.assign @cache, privateAcronyms
    console.log("loaded private acronyms from" + acroPrivPath)
```

**Comment by higs4281** [comment]
For us, If we load private, we don't need the public. The private is an enhanced version of the public.

But perhaps for other users it would make sense to load public first, then load private on top of that if it exists?

Loading both every time is harmless churning for us, I suppose.

**Comment by contolini** [comment]
Ah okay, I didn't even bother to compare the two files. The currently functionality is fine by me.
