### ISSUE TITLE
Allow multiple acronyms/definitions

### ISSUE THREAD

**Issue by vickumar1981** [cfpb/hubot-acrogov#6]
Perhaps the reddis store could be slightly modified to store an array/list of definitions for each key.

Just a thought.

**Comment by higs4281** [comment]
We already have some multiple definitions, like FSA, but they're just single entry strings with definitions separated by OR.

Would be nice to have a structure to it

**Comment by contolini** [comment]
Hmmm so current functionality:
1. user>> hubot define FSA as Flex Spending Account
2. user>> hubot define FSA as Full Speed Ahead
3. user>> hubot define FSA
4. hubot>> FSA stands for Full Speed Ahead

Proposed functionality:
1. user>> hubot define FSA as Flex Spending Account
2. user>> hubot define FSA as Full Speed Ahead
3. user>> hubot define FSA
4. hubot>> FSA stands for Flex Spending Account OR Full Speed Ahead

The tricky part comes with deleting definitions. If I `hubot stop defining FSA` should it delete all FSA definitions?

**Comment by higs4281** [comment]
i guess we'd need "stop defining X as Y"
also, current functionality is to not allow overwrite of a current definition. you can delete it and then redefine.

**Comment by contolini** [comment]
Cool, I guess we can have both commands "stop defining X" will delete all definitions and "stop defining X as Y" will delete only the specified definition.

**Comment by djdrisco** [comment]
I like the idea of updating the Redis store to allow using a different data structure. This would also allow  an acronym can have multiple definitions. (set or list perhaps)

**Comment by higs4281** [comment]
wanted to work out the interplay between our private definitions json and those added in brain.

I'll pursue a better storage model next.
